### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JamieKMorrison**
Updated the readme to include an extra sentence to prove that I can edit said file

### CODE REVIEW

**Comment by JamieKMorrison** [comment]
@JPodmore

**Comment by stuartmutter** [comment]
:+1: :8ball:

**Comment by JamieKMorrison** [comment]
🐑

**Comment by stuartmutter** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by stuartmutter** [comment]
:bird::bird::bird::bird::bird::bird:

**Comment by JamieKMorrison** [comment]
:trollface:

**Pull request merged**
